config/routes.rb
Rails.application.routes.draw do
  resources :mugs
  resources :owners
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mug.rb
class Mug < ApplicationRecord
  belongs_to :owner
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :mugs
  def full_name
    self.first_name + " " + self.last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mugs_controller.rb
class MugsController < ApplicationController
    def index
      @mugs = Mug.all
    end

    def show
      @mug = Mug.find(params[:id])
    end

    def new
      @mug = Mug.new
    end

    def create
      @mug = Mug.create(mug_params)
      redirect_to @owner
    end

    def edit
      @mug = Mug.find(params[:id])
    end

    def update
      @mug = Mug.find(params[:id])
      @mug.update(mug_params)
      redirect_to @mug
    end

    def destroy
      @mug = Mug.find(params[:id])
      @mug.destroy
      redirect_to mugs_path
    end

    private
      def mug_params
        params.require(:mug).permit(:first_name, :last_name, :age, :email)
      end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
    @owners = Owner.all
  end

  def show
    @owner = Owner.find(params[:id])
  end

  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.create(owner_params)
    redirect_to @owner
  end

  def edit
    @owner = Owner.find(params[:id])
  end

  def update
    @owner = Owner.find(params[:id])
    @owner.update(owner_params)
    redirect_to @owner
  end

  def destroy
    @owner = Owner.find(params[:id])
    @owner.destroy
    redirect_to owners_path
  end

  private
    def owner_params
      params.require(:owner).permit(:first_name, :last_name, :age, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mugs_helper.rb
module MugsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OwnerMugsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mugs/edit.html.erb
<h1>Edit Mug Form</h1>
<%=form_for @mug do |f|%>
<%=f.label 'name'%>
<%=f.text_field 'name'%><br>

<%=f.label 'thickness'%>
<%=f.number_field 'thickness'%><br>

<%=f.collection_select(:owner_id, Owner.all, :id, :full_name)%>

<%=f.submit "save"%>
<%end%>

app/views/mugs/index.html.erb
<h1>All Mugs Index</h1>
<ul>
  <%@mugs.each do |mug|%>
  <li> <%=link_to mug.name, mug_path(mug) %></li>
  <%end%>
</ul>

app/views/mugs/new.html.erb
<h1>New Mug Form</h1>
<%=form_for @mug do |f|%>
<%=f.label 'name'%>
<%=f.text_field 'name'%><br>

<%=f.label 'thickness'%>
<%=f.number_field 'thickness'%><br>

<%=f.collection_select(:owner_id, Owner.all, :id, :full_name)%>

<%=f.submit "add new mug"%>
<%end%>

app/views/mugs/show.html.erb
<h1>Mugs <%=@mug.name%>'s Page</h1>
<%= button_to "edit", edit_mug_path, method: :get%>
<%= button_to "delete", @mug, method: :delete %>

app/views/owners/edit.html.erb
<h1>Edit Owners Form</h1>
<%=form_for @owner do |f|%>
<%=f.label 'first_name'%>
<%=f.text_field 'first_name'%><br>

<%=f.label 'last_name'%>
<%=f.text_field 'last_name'%><br>

<%=f.label 'age'%>
<%=f.number_field 'age'%><br>

<%=f.label 'email'%>
<%=f.text_field 'email'%><br>

<%=f.submit "save"%>
<%end%>

app/views/owners/index.html.erb
<h1>All Owners Index</h1>
<ul>
  <%@owners.each do |owner|%>
  <li><%=link_to owner.full_name, owner_path(owner) %></li>
  <%end%>
</ul>

app/views/owners/new.html.erb
<h1>New Owner Form</h1>
<%=form_for @owner do |f|%>
<%=f.label 'first_name'%>
<%=f.text_field 'first_name'%><br>

<%=f.label 'last_name'%>
<%=f.text_field 'last_name'%><br>

<%=f.label 'age'%>
<%=f.number_field 'age'%><br>

<%=f.label 'email'%>
<%=f.text_field 'email'%><br>

<%=f.submit "add new owner"%>
<%end%>

app/views/owners/show.html.erb
<h1>Owners <%=@owner.full_name%>'s Page</h1>
<%= button_to "edit", edit_owner_path, method: :get%>
<%= button_to "delete", @owner, method: :delete %>